# Generated by Django 3.2.6 on 2021-09-07 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=14, unique=True)),
                ('address', models.CharField(max_length=40)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=14, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(height_field=400, upload_to='REMApp', width_field=360)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(height_field=300, upload_to='REMApp', width_field=260)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=14, unique=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('property_id', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=50, unique=True)),
                ('price', models.FloatField(max_length=150)),
                ('status', models.CharField(choices=[('SD', 'Sold'), ('FS', 'For Sale'), ('OC', 'Occupied'), ('TL', 'To-Let')], max_length=2)),
                ('image', models.ImageField(height_field=400, upload_to='REMApp', width_field=360)),
            ],
        ),
        migrations.CreateModel(
            name='Property_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=50)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='REMApp.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.TimeField()),
                ('comment', models.CharField(max_length=50)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='REMApp.admin')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='REMApp.client')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='REMApp.property')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_description', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('apppointmentStatus', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('AP', 'Approved'), ('PD', 'Pending'), ('OC', 'Occupied')], max_length=2)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='REMApp.admin')),
                ('agent_id', models.ManyToManyField(to='REMApp.Agent')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='REMApp.client')),
            ],
        ),
    ]
