# Generated by Django 3.2.6 on 2021-09-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REMApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='apppointmentStatus',
            new_name='appointmentStatus',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='id',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_id',
            new_name='property_code',
        ),
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(height_field=400, upload_to='', width_field=360),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(height_field=300, upload_to='', width_field=260),
        ),
    ]
